### ISSUE TITLE
Uncaught TypeError: Cannot read property 'null' of undefined

### ISSUE THREAD

**Issue by redVi** [bripkens/project-sidebar#12]
Only when project-sidebar is enabled. I see this message each time as I click on the document, opened in Atom. This bug appeared two days ago or few before. The output:

```
/Users/user/.atom/packages/project-sidebar/node_modules/react/lib/ReactMount.js:636
Stack Trace
TypeError: Cannot read property 'null' of undefined
    at Object.ReactMount.findReactContainerForID (/Users/user/.atom/packages/project-sidebar/node_modules/react/lib/ReactMount.js:636:50)
    at findParent (/Users/user/.atom/packages/project-sidebar/node_modules/react/lib/ReactEventListener.js:39:30)
    at handleTopLevelImpl (/Users/user/.atom/packages/project-sidebar/node_modules/react/lib/ReactEventListener.js:74:16)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/user/.atom/packages/project-sidebar/node_modules/react/lib/Transaction.js:134:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/user/.atom/packages/project-sidebar/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
    at Object.batchedUpdates (/Users/user/.atom/packages/project-sidebar/node_modules/react/lib/ReactUpdates.js:110:20)
    at ReactEventListener.dispatchEvent (/Users/user/.atom/packages/project-sidebar/node_modules/react/lib/ReactEventListener.js:174:20)
```

<img width="916" alt="bugtrace" src="https://cloud.githubusercontent.com/assets/2623486/15966366/08183c26-2f4d-11e6-9eeb-914ff2cdfe04.png">

**Comment by redVi** [comment]
I reinstalled this plugin and... all works again. No errors more. So, I don't now what is was, but I closed issue.
