### ISSUE TITLE
Failed to activate the project-sidebar package

### ISSUE THREAD

**Issue by mmacadamsphonecom** [bripkens/project-sidebar#4]
[Enter steps to reproduce below:]
1. Click "Packages > Project Sidebar > Toggle"

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [project-sidebar](https://github.com/bripkens/project-sidebar) package, v1.2.0
### Stack Trace

Failed to activate the project-sidebar package

```
At ENOENT: no such file or directory, open '/Users/mmacadams/.atom/projects.cson'

Error: ENOENT: no such file or directory, open '/Users/mmacadams/.atom/projects.cson'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.readFileSync (fs.js:396:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
    at Object.module.exports.readFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:158:21)
    at getProjects (/Users/mmacadams/.atom/packages/project-sidebar/lib/Sidebar.js:65:32)
    at getInitialState (/Users/mmacadams/.atom/packages/project-sidebar/lib/Sidebar.js:34:22)
    at new Constructor (/Users/mmacadams/.atom/packages/project-sidebar/node_modules/react/lib/ReactClass.js:853:54)
    at ReactCompositeComponentMixin.mountComponent (/Users/mmacadams/.atom/packages/project-sidebar/node_modules/react/lib/ReactCompositeComponent.js:135:16)
```
### Commands

```
     -3:45.2.0 window:install-shell-commands (ul.list-inline.tab-bar.inset-panel)
     -3:38.5.0 command-palette:toggle (ul.list-inline.tab-bar.inset-panel)
     -3:33.2.0 dev-live-reload:reload-all (atom-pane.pane.active)
     -3:29 merge-conflicts:detect (atom-pane.pane.active)
     -3:19.8.0 git-control:toggle (atom-pane.pane.active)
     -2:39.6.0 settings-view:uninstall-packages (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:27.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 project-sidebar:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{
  "core": {
    "projectHome": "~/repos/"
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-php, v0.3.6
color-picker, v2.0.7
git-control, v0.3.0
git-log, v0.4.1
merge-conflicts, v1.3.2
pigments, v0.8.0
project-sidebar, v1.2.0
tree-view-git-projects, v0.5.0
tree-view-git-status, v0.1.1
tualo-git-context, v0.6.10

# Dev
No dev packages
```

**Comment by bripkens** [comment]
As described in the README, you need to have the _project-manager_ addon configured properly as the _project-sidebar_ is using _project-manager_'s configuration file.

https://github.com/danielbrodin/atom-project-manager

**Comment by mmacadamsphonecom** [comment]
perhaps you could catch the error state and display a small pop-up window
with this info?

**Comment by bripkens** [comment]
@mmacadamsphonecom: I added an info popup and released a new version just now. Let me know whether there is anything else that you need.
